---
title: "Family Level Graph"
author: "Tianyi Xu"
date: "2024-12-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(here)
```

## Load data 

First we read in the data
```{r}
asv_abundance = t(read.csv(here("src", "ASV_Abundance_Table.csv")))
taxonomy_info = read.delim(here("src", "ASV_tax_assignments.txt"), sep = "\t", header = FALSE)
colnames(taxonomy_info) = c("ASV", "Taxanomy", "Count1", "Count2")
```

Process the data
```{r}
# Merge data
asv_info_row = asv_abundance[1, ]
asv_data_row = asv_abundance[-1, ]
colnames(asv_data_row) = asv_info_row
```

Add family information to the data
```{r}
# first extract the family information from the taxonomy
taxonomy_info$Family = sapply(taxonomy_info$Taxanomy, function(x) strsplit(x, ";")[[1]][5])

# covert to data frame
asv_data_row = as.data.frame(asv_data_row)
asv_data_row$ASV = rownames(asv_data_row)
# reorder the columns
asv_data_row = asv_data_row[, c("ASV", colnames(asv_data_row))]
rownames(asv_data_row) = NULL

# add the family information to the data
asv_data_row = asv_data_row %>% 
  left_join(taxonomy_info, by = "ASV")
```

Remove unecessary columns
```{r}
asv_data_row = asv_data_row %>% 
  select(-ASV.1, -Taxanomy, -Count1, -Count2)
```

Add a column for Magnaporthaceae family or other family
```{r}
asv_data_row$Magnaporthaceae = ifelse(asv_data_row$Family == "f__Magnaporthaceae", "Magnaporthaceae", "Other")

# if NA, then it is other family
asv_data_row$Magnaporthaceae[is.na(asv_data_row$Magnaporthaceae)] = "Other"
```

Calculate the relative abundance of Magnaporthaceae family and relative abundance of other family for each sample

```{r}
data_long = asv_data_row %>% 
  pivot_longer(cols = -c(ASV, Family, Magnaporthaceae), names_to = "Sample", values_to = "Abundance") %>%
  mutate(Abundance = as.numeric(Abundance)) %>%
  group_by(Sample, Magnaporthaceae) %>%
  summarise(Abundance = sum(Abundance), .groups = "drop") %>%
  group_by(Sample) %>%
  mutate(Relative_Abundance = Abundance / sum(Abundance) * 100)
```

Creating the plot
```{r}
plt = ggplot(data_long, aes(x = Sample, y = Relative_Abundance, fill = Magnaporthaceae)) +
    geom_bar(stat = "identity", position = "stack") +
    scale_fill_manual(values = c("Magnaporthaceae" = "coral", "Other" = "skyblue")) +
    labs(
        title = "Relative Abundance of Magnaporthaceae Family",
        x = "Root Samples",
        y = "Relative Abundance (%)",
        fill = "Family"
    ) +
    theme_minimal() +
    theme(
        axis.text.x = element_text(angle = 0, hjust = 1),
        legend.position = "right"
    )

plt
```

Save the plot as pdf    
```{r}
ggsave(here("src", "Magnaporthaceae_Family_Level_Graph.pdf"), plot = plt, width = 10, height = 6)
```

